### ISSUE TITLE
Model blowing up in the land with new topo file

### ISSUE THREAD

**Issue by kshedstrom** [mom-ocean/MOM6#1477]
I'm trying a new bathymetry. I have:
```
MINIMUM_DEPTH = 4.0
MASKING_DEPTH = 1.0
```
The bathymetry has not been clipped and ranges all the way down to -1300.

The traceback is:
```
#0  0x7fa0e98b856f in ???
#1  0x1f799dd in meridional_mass_flux
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM_continuity_PPM.F90:1191
#2  0x1fa7502 in __mom_continuity_ppm_MOD_continuity_ppm
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM_continuity_PPM.F90:167
#3  0x7675e6 in __mom_continuity_MOD_continuity
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM_continuity.F90:100
#4  0x125b2e1 in __mom_dynamics_split_rk2_MOD_step_mom_dyn_split_rk2
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM_dynamics_split_RK2.F90:558
#5  0x200bf1a in step_mom_dynamics
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM.F90:1071
#6  0x2011bce in __mom_MOD_step_mom
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/src/core/MOM.F90:790
#7  0x1740596 in __ocean_model_mod_MOD_update_ocean_model
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/MOM6/config_src/drivers/FMS_cap/ocean_model_MOM.F90:583
#8  0x8d4fa0 in coupler_main
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/coupler/coupler_main.F90:1086
#9  0x8e52e0 in main 
        at //import/c1/AKWATERS/kate/ESMG/ESMG-configs/src/coupler/coupler_main.F90:314
```
I have added some debug code, so this is referring to:
```
1188             if (dv_max_CFL(i) * visc_rem(i,k) > dy_S*CFL_dt - v(i,J,k)) then
1189               if (visc_rem(i,k) == 0.0) print *, 'VISC_REM', i+G%idg_offset,J+G%jdg_offset,k, &
1190                  dy_S, CFL_dt, v(i,J,k), visc_rem(i,k)
1191               dv_max_CFL(i) = (dy_S*CFL_dt - v(i,J,k)) / visc_rem(i,k)
1192             endif
```
which prints:  VISC_REM           1        1392           1   5226.4606933593750        1.6666666666666668E-003   2.5072916091180292E+034   0.0000000000000000

This is in the upper left corner of the domain, inside the land mask.

**Comment by kshedstrom** [comment]
I think this was fixed with a new set of the mosaic files.
